services:
  backend:
    build:
      context: ../backend
      dockerfile: ./Dockerfile
      args:
        env: "test"
    command: |
        bash -c "
        gunicorn src.main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --log-level=debug --timeout=60"
    environment:
      - PYTHONUNBUFFERED=0
      - PROJECT_NAME=test
      - VERSION=v1
      - DEVELOPER=nickatnight
      - ENV=test
    volumes:
      - /data:/data  # to access coverage.xml